ToDoList/Models/Assignment.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ToDoList.Models
{
    public class Assignment
    {

        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        public string? Details { get; set; } = "";
        public bool Checked { get; set; } = false;

        [ForeignKey("History")]
        public string HistoryId { get; set; } = DateTime.Now.ToString("d.M.yyyy");
        
    }
}

ToDoList/Models/ErrorViewModel.cs
namespace ToDoList.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoList/Models/History.cs
using System.ComponentModel.DataAnnotations;

namespace ToDoList.Models
{
    public class History
    {
        [Key]
        public string HistoryId { get; set; }
    }
}

ToDoList/Models/Task.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ToDoList.Models
{
    public class Task
    {

        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        public string Details { get; set; }
        public bool Checked { get; set; }

        [ForeignKey("HistoryRefId")]
        public DateTime MyProperty { get; set; }
    }
}

ToDoList/Controllers/AssignmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Security.Policy;
using System.Threading.Channels;
using System;
using ToDoList.Data;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class AssignmentController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AssignmentController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Assignment> tasks = _db.Assignments;
            IEnumerable<History> historys = _db.Historys;
            string date = DateTime.Now.ToString("d.M.yyyy");
            if (historys.ToList().Count == 0 || string.Compare(historys.Last().HistoryId, date) != 0)
            {
                return RedirectToAction("TodayHistory");
            }
            return View(tasks);
        }

        public IActionResult TodayHistory()
        {
           return View();
        }

        //GET
        public IActionResult CreateHistory()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        //I forget this and it took me a long time figuring this out
        public IActionResult CreateHistory(History obj)
        {
            string date = DateTime.Now.ToString("d.M.yyyy");
            if (string.Compare(date, obj.HistoryId) != 0)
            {
                ModelState.AddModelError("CustomError", @"The history date is not corresponding with today's date!
                                                          The format should be 'day.month.year' without leading zeros.
                                                          ");
            }
            if(ModelState.IsValid)
            {
                _db.Historys.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(obj);
        }

   

        //GET

        public IActionResult CreateAssignment()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateAssignment(Assignment obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Details == null)
                {
                    obj.Details = "";
                }
                _db.Assignments.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(obj) ;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, bool done)
        {
            var assignment = _db.Assignments.Find(id);
            if (assignment == null)
            {
                return NotFound();
            }
            assignment.Checked = done;
            _db.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        //GET
        public IActionResult Edit(int? id)
        {
            var assignment = _db.Assignments.Find(id);
            if (assignment == null)
            {
                return NotFound();
            }
            return View(assignment);
        }

        //POST
        [HttpPost] //if it is a pasto action we need to write attribute httppost
        [ValidateAntiForgeryToken] //this aswell
        public IActionResult Edit(Assignment obj)
        {
            if (ModelState.IsValid)
            {
                _db.Assignments.Update(obj);
                _db.SaveChanges(); //goes to the database and save the changes
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Delete(int? id)
        {

            var assignment = _db.Assignments.Find(id);
            if (assignment == null)
            {
                return NotFound();
            }
            return View(assignment);
        }

        //POST
        [HttpPost] //if it is a post action we need to write attribute httppost
        [ValidateAntiForgeryToken] //this aswell
        public IActionResult Delete(Assignment obj)
        {
            _db.Assignments.Remove(obj);
            _db.SaveChanges(); //goes to the database and save the changes
            return RedirectToAction("Index");
        }
    }


}

ToDoList/Controllers/HistoryController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoList.Data;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class HistoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public HistoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<History> historys = _db.Historys;
            return View(historys);
        }

        public IActionResult ShowAssignments(History obj)
        {
            IEnumerable<Assignment> assignments = _db.Assignments.Where(a => a.HistoryId == obj.HistoryId);
            return View(assignments);
        }


        //from view ShowAssignments passing obj here to work with, null obj appears
        public IActionResult ShowDetail(Assignment obj)
        {

            return View(obj);
        }
    }
}

ToDoList/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDoList/Views/Assignment/CreateAssignment.cshtml
@model Assignment

<form method="post">
    
    <div class=" border pt-3 mt-4">
        <!-- margin top(mt)-->
        <div class="row pb-2">
            <h2 class="text-primary">Create Task</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label asp-for="Details"></label>
            <textarea asp-for="Details" rows="3" class="form-control" ></textarea>
        </div>
        <button type="submit"  class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Assignment" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

<!--now the validation are done on client sides, so the side is not realoding, when validation is not valid. Thanks to this code-->
@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ToDoList/Views/Assignment/CreateHistory.cshtml
@model History
<form method="post">
    <div class=" border pt-3 mt-4">
        <!-- margin top(mt)-->
        <div class="row pb-2">
            <h2 class="text-primary">Create today's recorder</h2>
            <h2>@DateTime.Now.ToString("d.M.yyyy")</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="HistoryId"></label>
            <input asp-for="HistoryId" class="form-control" />
            <span asp-validation-for="HistoryId" class="text-danger"></span>
            <div asp-validation-summary="All" class="text-danger"></div>

        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Assignment" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

<!--now the validation are done on client sides, so the side is not realoding, when validation is not valid. Thanks to this code-->
@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ToDoList/Views/Assignment/Delete.cshtml
@model Assignment
<form method="post">
    <div class=" border pt-3 mt-4">
        <!-- margin top(mt)-->
        <div class="row pb-2">
            <h2 class="text-primary">Delete</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Details"></label>
            <textarea asp-for="Details" disabled class="form-control"></textarea>
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Assignment" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

ToDoList/Views/Assignment/Edit.cshtml
@model Assignment
<form method="post">
    <div class=" border pt-3 mt-4">
        <!-- margin top(mt)-->
        <div class="row pb-2">
            <h2 class="text-primary">Edit</h2>
            <hr />git
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label asp-for="Details"></label>
            <textarea asp-for="Details" class="form-control"></textarea>
            <span asp-validation-for="Details" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

ToDoList/Views/Assignment/Index.cshtml
@model IEnumerable<Assignment>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <!--'p-' moves dialognaly left-->
    <div class="row pt-4">
        <!--'pt'add a top padding-->
        <div class="col-6">
            <!--12 possible collmuns per row, so if we want 2 columms, its p-6 -->
            <h2 class="text-primary">Today's tasks</h2>
        </div>
        <div class="col-6 end text-end">
            <a asp-controller="Assignment" asp-action="CreateAssignment" class="btn btn-primary">
                <!--"btn btn-primary" bootstrap classes-->
                <i class="bi bi-plus-circle"></i> &nbsp; Create new task <!--&nbsp = space -->
            </a>
        </div>

    </div>
    <br />

</div>
<table class="table table-bordered table-striped" style="width:100%">
   <thead>
       <tr>
           <th>
               Today's tasks
           </th>
           
       </tr>
   </thead>
   <tbody>
        @foreach(var obj in Model)
        {
            @if (string.Compare(obj.HistoryId, DateTime.Now.ToString("d.M.yyyy")) == 0)
            {
                <tr>
                    <td width="50%">
                        @obj.Name
                      
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Assignment" asp-action="Edit" asp-route-id="@obj.Id"
                               class="btn btn-primary mx-2"><i class="bi bi-pencil-square">&nbsp;</i>Edit</a>
                        <a asp-controller="Assignment" asp-action="Delete" asp-route-id="@obj.Id"
                               class="btn btn-danger mx-2"><i class="bi bi-trash3">&nbsp;</i>Delete</a>
                    </div>
                </td>
            </tr>
            }
        }
    </tbody>
</table>

ToDoList/Views/Assignment/TodayHistory.cshtml
@{
    ViewData["Title"] = "TodayHistory";
}

<h1>Today's task recorder has not been created!</h1>
<div class="container p-3">
    <!--'p-' moves dialognaly left-->
    <div class="row pt-4">
        <!--'pt'add a top padding-->
        <div class="col-6 end text-left">
            <a asp-controller="Assignment" asp-action="CreateHistory" class="btn btn-primary">
                <!--"btn btn-primary" bootstrap classes-->
                <i class="bi bi-plus-circle"></i> &nbsp; Create recorder <!--&nbsp = space -->
            </a>
        </div>

    </div>
    <br />
</div>

ToDoList/Views/History/Index.cshtml
@model IEnumerable<History>
@{
    ViewData["Title"] = "Index";
}

<h1>History preview</h1>

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Previous days
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.HistoryId
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="History" asp-action="ShowAssignments" asp-route-id="@obj.HistoryId"
                           class="btn btn-primary mx-2"><i class="bi bi-card-list"></i>Previous tasks</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

ToDoList/Views/History/ShowAssignments.cshtml
@model IEnumerable<Assignment>
@{
    ViewData["Title"] = "Index";
}

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
            @if (Model.Count() != 0)
            {
                @Model.First().HistoryId
            }
            else
            {
                <th>
                This day there were no tasks
                </th>
            }
            </th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            @if (string.Compare(obj.HistoryId, DateTime.Now.ToString("d.M.yyyy")) == 0)
            {
                <tr>
                    <td width="50%">
                        @obj.Name

                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="History" asp-action="ShowDetail" asp-route-id="@obj.Id"
                               class="btn btn-primary mx-2"><i class="bi bi-pencil-square">&nbsp;</i>Show Details</a>
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

ToDoList/Views/History/ShowDetail.cshtml
@model Assignment
<form method="post">
    <div class=" border pt-3 mt-4">
        <!-- margin top(mt)-->
        <div class="row pb-2">
            <h2 class="text-primary">Edit</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Details"></label>
            <textarea disabled asp-for="Details" class="form-control"></textarea>
            <span asp-validation-for="Details" class="text-danger"></span>
        </div>
        <a asp-controller="History" asp-action="ShowAssignment" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

ToDoList/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Today's to do list!</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoList.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assignment" asp-action="Index">Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="History" asp-action="Index">History</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ToDoList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.min.js" integrity="sha384-heAjqF+bCxXpCWLa6Zhcp4fu20XoNIA98ecBC1YkdXhszjoejr5y9Q77hIrv8R9i" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoList/Views/Task/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>